services:
  samba:
    container_name: samba
    image: gnr092/samba:${SMB_VERSION:-release}
    environment:
      - SAMBA_USER=${SMB_USER}
      - SAMBA_PASS=${SMB_PASSWORD}
    ports:
      - "137-138:137-138/udp"  # NetBIOS (nmbd)
      - "139:139/tcp"          # Samba (smbd)
      - "445:445/tcp"          # Samba (smbd)
    volumes:
      - ${SMB_DIRECTORY}:/cpublic
    env_file:
      - .env
    restart: unless-stopped